@host =  https://localhost:44350

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Mariam",
    "lastName": "Qassem",
    "email": "artist.mariam.qassem",
    "password": "password"
}